[tool.black]
line-length = 88
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 88

[tool.ruff]
line-length = 88
select = ["E", "F", "I", "UP", "B", "C4"]
ignore = ["E501"]
target-version = "py310"
